### ISSUE TITLE
DB error at generation

### ISSUE THREAD

**Issue by YovaKem** [ufal/augpt#5]
I am attempting to train an ablated model without backtranslation, pre-training and data cleaning so I'm using the following command

`./train_multiwoz.py --train-dataset multiwoz-2.0-train --dev-dataset multiwoz-2.0-val --model gpt2 --response-loss unlikelihood --epochs 10 --fp16 --gradient-accumulation-steps 4`

This works fine, but then the generation

`./generate.py --model <model> --dataset multiwoz-2.0-test --file predictions.txt`

throws this error 20%  into the process:

``` Traceback (most recent call last):
  File "./generate.py", line 177, in <module>
    orable_database_results=args.oracle_db)
  File "./generate.py", line 131, in generate_predictions
    conversation = pipeline(conversation)
  File "/home/USER/augpt/pipelines.py", line 252, in __call__
    for oracle_db, bs in zip(oracle_dbs_results, beliefs)]
  File "/home/USER/augpt/pipelines.py", line 252, in <listcomp>
    for oracle_db, bs in zip(oracle_dbs_results, beliefs)]
  File "<string>", line 204, in __call__
  File "<string>", line 191, in query_domain
sqlite3.OperationalError: no such column: destination 
```

Is this something you encountered during your work and do you have thoughts on how I could go about debugging it? Thanks!

NB: Running the generation with jkulhanek/augpt-mw-20 works just fine.

**Comment by jkulhanek** [comment]
It has never happen to us and the probability of this happening should be low. A quick fix would be to add "destination" to ignored slots [here](https://github.com/ufal/augpt/blob/fa8a57961ed1d8fe6099978c489c0b0f8956d64e/scripts/download_multiwoz.py#L909). After this, you have to regenerate the dataset.

**Comment by YovaKem** [comment]
Thanks, that sorted it out!
